# This file was automatically generated by SDx
set xocc_optimize_level 0
set_property SEVERITY {Warning} [get_drc_checks HDPR-5]
set_param logicopt.enableBUFGinsertHFN 0

# init kernel_pin_freqs
set kernel_pin_freqs(xcl_design_i/expanded_region/u_ocl_region/DATA_CLK) 300
set kernel_pin_freqs(xcl_design_i/expanded_region/u_ocl_region/KERNEL_CLK2) 500
set worst_negative_slack 0
source /software/Xilinx/SDx_2017.1/SDx/2017.1/scripts/ocl/ocl_util.tcl
namespace import ocl_util::*
