# This file was automatically generated by SDx

# generate cookie file for messaging
write_cookie_file_impl "bin_mmult_hw"

# utilization reports
report_utilization_impl true "mmult" "xcl_design_i/expanded_region/u_ocl_region" "routed"

# timing analysis and frequencly scaling
if { ![report_timing_and_scale_freq true "xcl_design_i/expanded_region/u_ocl_region" "kernel_clock_freqs {DATA_CLK {is_user_set false freq_orig 300 freq 300} KERNEL_CLK2 {is_user_set false freq_orig 500 freq 500}} system_clock_freqs {} worst_negative_slack 0 lock_slack_threshold 1.2 max_frequency 500 min_frequency 60 error_on_hold_violation true skip_timing_and_scaling false" "dr"] } {
  return false
}
