# 
# Hls run script generated by SDAccel
# 

set xocc_optimize_level 0
open_project mmult
set_top mmult
add_files "/root/huaweicloud-fpga/fp1/hardware/sdaccel_design/user/mmult/src/mmult.c"
open_solution solution_OCL_REGION_0
set_part xcvu9p-flgb2104-2-i
create_clock -period 300MHz -name default
set_clock_uncertainty 0.900000
config_rtl -register_reset
config_interface -m_axi_addr64
config_schedule -relax_ii_for_timing
config_compile -pipeline_loops 64
config_compile -name_max_length 256
csynth_design
export_design -format ipxact -kernel_drc -sdaccel
close_project
puts "Vivado HLS completed successfully"
exit
